kernel.config:
    charset:       UTF-8
    error_handler: null

web.config:
    router:     { resource: "%kernel.root_dir%/config/routing.yml" }
    validation: { enabled: true, annotations: true }

web.templating:
    escaping:       htmlspecialchars
    #assets_version: SomeVersionScheme

tag.config: ~


devorigin.config: ~

doctrine.orm:
  default_entity_manager:   default
  entity_managers:
    default:
      connection:           default