imports:
    - { resource: config.yml }

web.config:
    router:   { resource: "%kernel.root_dir%/config/routing_dev.yml" }
    profiler: { only_exceptions: false }

webprofiler.config:
    toolbar: true
    intercept_redirects: true

zend.logger:
    priority: debug
    path:     %kernel.root_dir%/logs/%kernel.environment%.log
 
doctrine.dbal:
  connections:
    default:
      driver:   PDOMySql
      dbname:   devorigin_sf2
      host: 127.0.0.1
      user:     root
      password: root
      port: ~