imports:
  - { resource: config.yml }

doctrine.dbal:
  connections:
    default:
      driver:   PDOMySql
      dbname:   devorigin_sf2
      host: 127.0.0.1
      user:     root
      password: root
      port: ~
