app.config:
    charset:       UTF-8
    error_handler: null
    router:     { resource: "%kernel.root_dir%/config/routing.yml" }
    validation: { enabled: true, annotations: true }
    templating:
        escaping: htmlspecialchars

twig.config: ~

tag.config: ~

menu.templating: ~

devorigin.config: ~

doctrine.orm:
  default_entity_manager:   default
  entity_managers:
    default:
      connection:           default
