#!/usr/bin/env php
<?php

require_once __DIR__.'/DevoriginKernel.php';

use Symfony\Framework\FoundationBundle\Console\Application;

$kernel = new DevoriginKernel('dev', true);

$application = new Application($kernel);
$application->run();
