<?php

namespace Bundle\NewsBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends EntityRepository
{

    public function findLatestNewsSortedBy($field, $order='desc', $nb = null)
    {
        $qb = $this->createQueryBuilder('n');
        $qb->orderBy('n.'.$field, $order);
        $query = $qb->getQuery();
        if(null !== $nb) {
            $query->setMaxResults($nb);
        }

        return $query->execute();
    }

}